### ISSUE TITLE
Add Bump task

### ISSUE THREAD

**Issue by danielfttorres** [FastGap/fastgap#16]
How about add [grunt-bump](https://github.com/vojtajina/grunt-bump) for change package version value in some files (package.json, bower.json etc) with a simple command (e.g.: grunt bump --setversion=0.x.x)? @pragmaticivan @GustavoCostaW @mayroncachina

**Comment by pragmaticivan** [comment]
Go ahead brow! @danielfeelfine

**Comment by danielfttorres** [comment]
fix in: c7d8eb1
