### ISSUE TITLE
Mudança iScroll to Overthrow

### ISSUE THREAD

**Issue by GustavoCostaW** [FastGap/fastgap#8]
Pelos meus testes o http://filamentgroup.github.io/Overthrow/ é MUITO mais rápido que o iScroll, ele usa o scroll nativo do aparelho, vamos começar os testes para a futura implementação.

**Comment by mayroncachina** [comment]
Pelo que vi aqui de fato é mais rápido.
Não testei dentro do fastgap, mais de outro projeto, foi muito mais eficiente e sem aquele bug chato de "travar" a tela...

Porém ele é mais "cru", se é que me entende, não tem funções interessantes como aquela do push refresh (estilo facebook para atualizar a pagina puxando o conteudo para baixo)....

**Comment by GustavoCostaW** [comment]
@mayroncachina podemos criar na mão, por exemplo, ele não tinha função de quando chegar no final ele carregar + conteudo, eu criei na mão, verifica se o cara desceu com os calculos se sim carrega + conteudo, e roda super liso, http://pastebin.com/pZynLSRX

pelo o que eu percebi do iScroll ele cria tudo na mão, mas o navegador já faz isso, eu desci umas 10x com o Android com esse texto fake acima e algumas imagens e rodou muito bem.

cc @pragmaticivan

**Comment by GustavoCostaW** [comment]
@mayroncachina 

http://usehook.com & http://www.idangero.us/sliders/swiper/demos/main-demos/18-pull-to-refresh.html 

sem iSCROLL

**Comment by GustavoCostaW** [comment]
implemented, close https://github.com/FastGap/fastgap/commit/e97049fbf9173201da1712fd7fdb9f162472ac9a
